# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "CLI for WonderTwin — behavioral twins for third-party APIs"
  homepage "https://wondertwin.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WonderTwin-AI/wondertwin/releases/download/v0.1.0/wondertwin_0.1.0_darwin_amd64.tar.gz"
      sha256 "9b1e93c3f6cdfa4bd4379bd9628994f99d68ccd0275bfa5da1f2642a65c9d659"

      def install
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WonderTwin-AI/wondertwin/releases/download/v0.1.0/wondertwin_0.1.0_darwin_arm64.tar.gz"
      sha256 "f320fd6af8abae44c690616678bb22bbd8ce6eb15b09ce050df1868bab1daa04"

      def install
        bin.install "wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WonderTwin-AI/wondertwin/releases/download/v0.1.0/wondertwin_0.1.0_linux_amd64.tar.gz"
      sha256 "70fcc24155a23171157c8ffb274bac55c353e72533197bc1d387283d9b44c81a"
      def install
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WonderTwin-AI/wondertwin/releases/download/v0.1.0/wondertwin_0.1.0_linux_arm64.tar.gz"
      sha256 "9b0304b91d1d0a01b4004b99765d5a059a5656d3d171e8e2c7130b1f6b56b555"
      def install
        bin.install "wt"
      end
    end
  end

  test do
    system "#{bin}/wt", "version"
  end
end
